#! /bin/sh

# Launch polybar
polybar -r main &


# Launch sxhkd
sxhkd &

# Launch notification server
dunst &

# Autohide the cursor when inactive
unclutter --ignore-scrolling &

# Set the cursor
xsetroot -cursor_name left_ptr 

# Desktops
bspc monitor -d I II III 

# Border and Gap
bspc config border_width         2
bspc config window_gap           2

# Configuration
bspc config split_ratio          0.50

# Mouse
bspc config click_to_focus	 	button1
bspc config focus_follows_pointer 	true

# Monocle mode settings
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true

# Colors
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"

# Rules
bspc rule -a Google-chrome desktop=II state=tiled follow=on

bspc config external_rules_command $HOME/.config/bspwm/bspwm-external-rules;

